/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FCargosAdministrador.java
 *
 * Created on 26-may-2011, 9:31:22
 */

package view;

import bo.usfx.nuevoAmanecer.controller.CGuiCargosAdministrador;
import java.awt.Cursor;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Luis Molina
 */
public class GuiCargosAdministrador extends javax.swing.JFrame {

    /** Creates new form FCargosAdministrador */
    public GuiCargosAdministrador() {
        control = new CGuiCargosAdministrador(this);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuFormularios = new javax.swing.JPopupMenu();
        jMenuItemAgregar = new javax.swing.JMenuItem();
        jPopupMenuPermisosFormularios = new javax.swing.JPopupMenu();
        jTabbedPaneCargos = new javax.swing.JTabbedPane();
        pnlGestionarCargos = new javax.swing.JPanel();
        pnlBotones = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jScrollPaneCargos = new javax.swing.JScrollPane();
        jTableCargos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        pnlCampos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextField();
        pnlGestionarPermisos = new javax.swing.JPanel();
        lblDatoCargo = new javax.swing.JLabel();
        jScrollPanePermisosInterfaces = new javax.swing.JScrollPane();
        jTablePermisosInterfaces = new javax.swing.JTable();
        pnlConfirmarPermisos = new javax.swing.JPanel();
        btnModificarPermisos = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnDescargarPermisos = new javax.swing.JButton();
        jScrollPaneInterfaces = new javax.swing.JScrollPane();
        jTableInterfaces = new javax.swing.JTable();

        jMenuItemAgregar.setText("Agregar Formulario");
        jMenuItemAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarActionPerformed(evt);
            }
        });
        jPopupMenuFormularios.add(jMenuItemAgregar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPaneCargos.setBackground(new java.awt.Color(204, 222, 235));
        jTabbedPaneCargos.setOpaque(true);

        pnlGestionarCargos.setLayout(new java.awt.BorderLayout());

        pnlBotones.setBackground(new java.awt.Color(255, 243, 189));
        pnlBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBotones.setPreferredSize(new java.awt.Dimension(574, 50));
        pnlBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 7));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setActionCommand("nuevo");
        btnNuevo.addActionListener(control);
        btnNuevo.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnNuevo.setToolTipText("Registrar nuevo Cargo");
        pnlBotones.add(btnNuevo);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Modificar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setActionCommand("editar");
        btnEditar.addActionListener(control);
        btnEditar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnEditar.setToolTipText("Modificar el Registro Seleccionado");
        pnlBotones.add(btnEditar);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Ok.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setActionCommand("aceptar");
        btnAceptar.addActionListener(control);
        btnAceptar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnAceptar.setToolTipText("Guardar los Realizados");
        pnlBotones.add(btnAceptar);

        btnCancelar.setText("Cancelar");
        btnCancelar.setActionCommand("cancelar");
        btnCancelar.addActionListener(control);
        btnCancelar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCancelar.setToolTipText("Cancelar la Operación Actual");
        pnlBotones.add(btnCancelar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Delete.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setActionCommand("eliminar");
        btnEliminar.addActionListener(control);
        btnEliminar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnEliminar.setToolTipText("Eliminar el Registro Seleccionado");
        pnlBotones.add(btnEliminar);

        btnCerrar.setText("Cerrar");
        btnCerrar.setActionCommand("cerrar");
        btnCerrar.addActionListener(control);
        btnCerrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCerrar.setToolTipText("Cerrar el Formulario Actual");
        pnlBotones.add(btnCerrar);

        pnlGestionarCargos.add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        jScrollPaneCargos.setBackground(new java.awt.Color(204, 222, 235));
        jScrollPaneCargos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Cargos Disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTableCargos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cargo", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneCargos.setViewportView(jTableCargos);
        jTableCargos.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableCargos.getColumnModel().getColumn(1).setPreferredWidth(200);

        pnlGestionarCargos.add(jScrollPaneCargos, java.awt.BorderLayout.CENTER);

        jSeparator1.setBackground(new java.awt.Color(204, 222, 235));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setOpaque(true);
        pnlGestionarCargos.add(jSeparator1, java.awt.BorderLayout.PAGE_START);

        pnlCampos.setBackground(new java.awt.Color(204, 222, 235));
        pnlCampos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos:"));
        pnlCampos.setPreferredSize(new java.awt.Dimension(251, 233));

        jLabel1.setText("Codigo");
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 14));
        pnlCampos.add(jLabel1);

        txtCodigo.setEditable(false);
        txtCodigo.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlCampos.add(txtCodigo);

        jLabel2.setText("Nombre");
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 14));
        pnlCampos.add(jLabel2);

        txtNombre.setPreferredSize(new java.awt.Dimension(150, 20));
        txtNombre.addKeyListener(control);
        pnlCampos.add(txtNombre);

        jLabel3.setText("Descripcion");
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 14));
        pnlCampos.add(jLabel3);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(150, 80));

        txtDescripcion.setPreferredSize(new java.awt.Dimension(150, 20));
        jScrollPane1.setViewportView(txtDescripcion);

        pnlCampos.add(jScrollPane1);

        pnlGestionarCargos.add(pnlCampos, java.awt.BorderLayout.LINE_START);

        jTabbedPaneCargos.addTab("Gestinar Cargos", pnlGestionarCargos);

        pnlGestionarPermisos.setLayout(new java.awt.BorderLayout());

        lblDatoCargo.setBackground(new java.awt.Color(204, 222, 235));
        lblDatoCargo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDatoCargo.setText("Cargo Actualmente Seleccionado :");
        lblDatoCargo.setOpaque(true);
        pnlGestionarPermisos.add(lblDatoCargo, java.awt.BorderLayout.NORTH);

        jScrollPanePermisosInterfaces.setPreferredSize(new java.awt.Dimension(450, 338));

        jTablePermisosInterfaces.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanePermisosInterfaces.setViewportView(jTablePermisosInterfaces);

        pnlGestionarPermisos.add(jScrollPanePermisosInterfaces, java.awt.BorderLayout.CENTER);

        pnlConfirmarPermisos.setBackground(new java.awt.Color(255, 243, 189));
        pnlConfirmarPermisos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlConfirmarPermisos.setPreferredSize(new java.awt.Dimension(574, 50));
        pnlConfirmarPermisos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnModificarPermisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Modificar.png"))); // NOI18N
        btnModificarPermisos.setText("Modificar");
        btnModificarPermisos.setActionCommand("modificarPermisos");
        btnModificarPermisos.addActionListener(control);
        btnModificarPermisos.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnModificarPermisos.setToolTipText("Modificar los Permisos");
        pnlConfirmarPermisos.add(btnModificarPermisos);

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Ok.png"))); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setActionCommand("confirmar");
        btnConfirmar.addActionListener(control);
        btnConfirmar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnConfirmar.setToolTipText("Confirmar los Cambios de Permisos Realizados");
        pnlConfirmarPermisos.add(btnConfirmar);

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Dar de Baja.png"))); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.setActionCommand("removerPermisos");
        btnRemover.addActionListener(control);
        btnRemover.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnRemover.setToolTipText("Remover el permiso Seleccionado");
        pnlConfirmarPermisos.add(btnRemover);

        btnAgregar.setText("Agregar");
        btnAgregar.setActionCommand("agregarFormulario");
        btnAgregar.addActionListener(control);
        btnAgregar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnAgregar.setToolTipText("Agregar Formulario");
        pnlConfirmarPermisos.add(btnAgregar);

        btnDescargarPermisos.setText("Cancelar");
        btnDescargarPermisos.setActionCommand("descargarPermisos");
        btnDescargarPermisos.addActionListener(control);
        btnDescargarPermisos.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnDescargarPermisos.setToolTipText("Descartar los cambios realizados");
        pnlConfirmarPermisos.add(btnDescargarPermisos);

        pnlGestionarPermisos.add(pnlConfirmarPermisos, java.awt.BorderLayout.SOUTH);

        jScrollPaneInterfaces.setPreferredSize(new java.awt.Dimension(152, 363));

        jTableInterfaces.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneInterfaces.setViewportView(jTableInterfaces);

        pnlGestionarPermisos.add(jScrollPaneInterfaces, java.awt.BorderLayout.LINE_END);

        jTabbedPaneCargos.addTab("Gestionar Permisos", pnlGestionarPermisos);

        getContentPane().add(jTabbedPaneCargos, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAgregarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiCargosAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnDescargarPermisos;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificarPermisos;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItemAgregar;
    private javax.swing.JPopupMenu jPopupMenuFormularios;
    private javax.swing.JPopupMenu jPopupMenuPermisosFormularios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneCargos;
    private javax.swing.JScrollPane jScrollPaneInterfaces;
    private javax.swing.JScrollPane jScrollPanePermisosInterfaces;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPaneCargos;
    private javax.swing.JTable jTableCargos;
    private javax.swing.JTable jTableInterfaces;
    private javax.swing.JTable jTablePermisosInterfaces;
    private javax.swing.JLabel lblDatoCargo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlCampos;
    private javax.swing.JPanel pnlConfirmarPermisos;
    private javax.swing.JPanel pnlGestionarCargos;
    private javax.swing.JPanel pnlGestionarPermisos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
    public CGuiCargosAdministrador control;
    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnCerrar() {
        return btnCerrar;
    }

    public JButton getBtnConfirmar() {
        return btnConfirmar;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JButton getBtnModificarPermisos() {
        return btnModificarPermisos;
    }

    public JButton getBtnNuevo() {
        return btnNuevo;
    }

    public JButton getBtnRemover() {
        return btnRemover;
    }

    public JTable getjTableCargos() {
        return jTableCargos;
    }

    public JTable getjTablePermisosInterfaces() {
        return jTablePermisosInterfaces;
    }

    public JTable getjTableInterfaces() {
        return jTableInterfaces;
    }
    

    public JTextField getTxtCodigo() {
        return txtCodigo;
    }

    public JTextField getTxtDescripcion() {
        return txtDescripcion;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public JTabbedPane getjTabbedPaneCargos() {
        return jTabbedPaneCargos;
    }

    public JPanel getPnlGestionarCargos() {
        return pnlGestionarCargos;
    }

    public JPanel getPnlGestionarPermisos() {
        return pnlGestionarPermisos;
    }

    public JScrollPane getjScrollPaneInterfaces() {
        return jScrollPaneInterfaces;
    }

    public JButton getBtnDescargarPermisos() {
        return btnDescargarPermisos;
    }

    public JLabel getLblDatoCargo() {
        return lblDatoCargo;
    }

    public JScrollPane getjScrollPanePermisosInterfaces() {
        return jScrollPanePermisosInterfaces;
    }

    public JPopupMenu getjPopupMenuFormularios() {
        return jPopupMenuFormularios;
    }

    public JPopupMenu getjPopupMenuPermisosFormularios() {
        return jPopupMenuPermisosFormularios;
    }

    
    
    
    
}
