/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


package view;

import bo.usfx.nuevoAmanecer.controller.CGuiEccd;
import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;


public class GuiEccd extends javax.swing.JFrame {

    /** Creates new form GuiEccd */
    public GuiEccd() {
        control = new CGuiEccd(this);
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jPanel40 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jPanel47 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        txtNroCaso = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtTalla = new javax.swing.JTextField();
        txtPesoTalla = new javax.swing.JTextField();
        cBoxSevenN = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtNumeroCasoBusqueda = new javax.swing.JTextField();
        btnBuscarModificacion = new javax.swing.JButton();
        dateFechaRegistroEdicion = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        txtNroCasoE = new javax.swing.JTextField();
        txtNombreE = new javax.swing.JTextField();
        txtSexoE = new javax.swing.JTextField();
        txtFechaE = new javax.swing.JTextField();
        txtPesoE = new javax.swing.JTextField();
        txtTallaE = new javax.swing.JTextField();
        txtPesoTallaE = new javax.swing.JTextField();
        cBoxSevenE = new javax.swing.JComboBox();
        jPanel39 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtNumeroCasoEliminacion = new javax.swing.JTextField();
        btnBuscarEliminacion = new javax.swing.JButton();
        jPanel85 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableEliminar1 = new javax.swing.JTable();
        jPanel38 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/BarraPequena - copia.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setForeground(new java.awt.Color(63, 120, 204));
        jLabel1.setText("CONTROL NUTRICIONAL DE MENORES DE 5 AÑOS");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/BarraPequena - copia.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 222, 235));

        jPanel8.setBackground(new java.awt.Color(255, 243, 189));

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Guardar.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setActionCommand("registrar");
        btnRegistrar.addActionListener(control);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setActionCommand("nuevo");
        btnNuevo.addActionListener(control);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevo)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnNuevo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel40.setBackground(new java.awt.Color(204, 222, 235));
        jPanel40.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Introducir Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jPanel41.setBackground(new java.awt.Color(255, 243, 189));
        jPanel41.setMaximumSize(new java.awt.Dimension(645, 85));
        jPanel41.setLayout(new java.awt.BorderLayout());

        jPanel42.setBackground(new java.awt.Color(255, 243, 189));
        jPanel42.setMaximumSize(new java.awt.Dimension(625, 60));
        jPanel42.setMinimumSize(new java.awt.Dimension(625, 60));
        jPanel42.setPreferredSize(new java.awt.Dimension(625, 60));
        jPanel42.setLayout(new javax.swing.BoxLayout(jPanel42, javax.swing.BoxLayout.LINE_AXIS));

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Nº CASO");
        jLabel48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel48.setMaximumSize(new java.awt.Dimension(65, 60));
        jLabel48.setMinimumSize(new java.awt.Dimension(65, 60));
        jLabel48.setPreferredSize(new java.awt.Dimension(65, 60));
        jPanel42.add(jLabel48);

        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("NOMBRE");
        jLabel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel49.setMaximumSize(new java.awt.Dimension(140, 60));
        jLabel49.setMinimumSize(new java.awt.Dimension(140, 60));
        jLabel49.setPreferredSize(new java.awt.Dimension(140, 60));
        jPanel42.add(jLabel49);

        jPanel43.setBackground(new java.awt.Color(255, 243, 189));
        jPanel43.setMaximumSize(new java.awt.Dimension(70, 60));
        jPanel43.setLayout(new java.awt.BorderLayout());

        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("SEXO");
        jLabel50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel50.setMaximumSize(new java.awt.Dimension(70, 30));
        jLabel50.setMinimumSize(new java.awt.Dimension(70, 30));
        jLabel50.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel43.add(jLabel50, java.awt.BorderLayout.PAGE_START);

        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("F/M");
        jLabel51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel51.setMaximumSize(new java.awt.Dimension(70, 30));
        jLabel51.setMinimumSize(new java.awt.Dimension(70, 30));
        jLabel51.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel43.add(jLabel51, java.awt.BorderLayout.CENTER);

        jPanel42.add(jPanel43);

        jPanel44.setBackground(new java.awt.Color(255, 243, 189));
        jPanel44.setMaximumSize(new java.awt.Dimension(90, 60));
        jPanel44.setLayout(new java.awt.BorderLayout());

        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("NCTO.");
        jLabel52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel52.setMaximumSize(new java.awt.Dimension(90, 30));
        jLabel52.setMinimumSize(new java.awt.Dimension(90, 30));
        jLabel52.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel44.add(jLabel52, java.awt.BorderLayout.CENTER);

        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("FECHA");
        jLabel53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel53.setMaximumSize(new java.awt.Dimension(90, 30));
        jLabel53.setMinimumSize(new java.awt.Dimension(90, 30));
        jLabel53.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel44.add(jLabel53, java.awt.BorderLayout.PAGE_START);

        jPanel42.add(jPanel44);

        jPanel45.setBackground(new java.awt.Color(255, 243, 189));
        jPanel45.setMaximumSize(new java.awt.Dimension(65, 60));
        jPanel45.setLayout(new java.awt.BorderLayout());

        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Kgrs.");
        jLabel54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel54.setMaximumSize(new java.awt.Dimension(65, 30));
        jLabel54.setMinimumSize(new java.awt.Dimension(65, 30));
        jLabel54.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel45.add(jLabel54, java.awt.BorderLayout.CENTER);

        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("PESO");
        jLabel55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel55.setMaximumSize(new java.awt.Dimension(65, 30));
        jLabel55.setMinimumSize(new java.awt.Dimension(65, 30));
        jLabel55.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel45.add(jLabel55, java.awt.BorderLayout.PAGE_START);

        jPanel42.add(jPanel45);

        jPanel46.setBackground(new java.awt.Color(255, 243, 189));
        jPanel46.setMaximumSize(new java.awt.Dimension(65, 60));
        jPanel46.setLayout(new java.awt.BorderLayout());

        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("Cms.");
        jLabel56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel56.setMaximumSize(new java.awt.Dimension(65, 30));
        jLabel56.setMinimumSize(new java.awt.Dimension(65, 30));
        jLabel56.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel46.add(jLabel56, java.awt.BorderLayout.CENTER);

        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("TALLA");
        jLabel57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel57.setMaximumSize(new java.awt.Dimension(65, 30));
        jLabel57.setMinimumSize(new java.awt.Dimension(65, 30));
        jLabel57.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel46.add(jLabel57, java.awt.BorderLayout.PAGE_START);

        jPanel42.add(jPanel46);

        jPanel47.setBackground(new java.awt.Color(255, 243, 189));
        jPanel47.setMaximumSize(new java.awt.Dimension(65, 60));
        jPanel47.setLayout(new java.awt.BorderLayout());

        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("TALLA");
        jLabel58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel58.setMaximumSize(new java.awt.Dimension(65, 30));
        jLabel58.setMinimumSize(new java.awt.Dimension(65, 30));
        jLabel58.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel47.add(jLabel58, java.awt.BorderLayout.CENTER);

        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("PESO/");
        jLabel59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel59.setMaximumSize(new java.awt.Dimension(65, 30));
        jLabel59.setMinimumSize(new java.awt.Dimension(65, 30));
        jLabel59.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel47.add(jLabel59, java.awt.BorderLayout.PAGE_START);

        jPanel42.add(jPanel47);

        jPanel48.setBackground(new java.awt.Color(255, 243, 189));
        jPanel48.setMaximumSize(new java.awt.Dimension(65, 60));
        jPanel48.setLayout(new java.awt.BorderLayout());

        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("(SVEN)");
        jLabel60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel60.setMaximumSize(new java.awt.Dimension(65, 30));
        jLabel60.setMinimumSize(new java.awt.Dimension(65, 30));
        jLabel60.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel48.add(jLabel60, java.awt.BorderLayout.CENTER);

        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("EST.NUT.");
        jLabel61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel61.setMaximumSize(new java.awt.Dimension(65, 30));
        jLabel61.setMinimumSize(new java.awt.Dimension(65, 30));
        jLabel61.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel48.add(jLabel61, java.awt.BorderLayout.PAGE_START);

        jPanel42.add(jPanel48);

        jPanel41.add(jPanel42, java.awt.BorderLayout.CENTER);

        jPanel49.setMaximumSize(new java.awt.Dimension(625, 25));
        jPanel49.setMinimumSize(new java.awt.Dimension(625, 25));
        jPanel49.setPreferredSize(new java.awt.Dimension(625, 25));
        jPanel49.setLayout(new javax.swing.BoxLayout(jPanel49, javax.swing.BoxLayout.LINE_AXIS));

        txtNroCaso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNroCaso.setMaximumSize(new java.awt.Dimension(65, 25));
        txtNroCaso.setMinimumSize(new java.awt.Dimension(65, 25));
        txtNroCaso.setPreferredSize(new java.awt.Dimension(65, 25));
        txtNroCaso.getDocument().addDocumentListener(control);
        txtNroCaso.addKeyListener(control);
        jPanel49.add(txtNroCaso);

        txtNombre.setEditable(false);
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombre.setMaximumSize(new java.awt.Dimension(140, 25));
        txtNombre.setMinimumSize(new java.awt.Dimension(140, 25));
        txtNombre.setPreferredSize(new java.awt.Dimension(140, 25));
        jPanel49.add(txtNombre);

        txtSexo.setEditable(false);
        txtSexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSexo.setMaximumSize(new java.awt.Dimension(70, 25));
        txtSexo.setMinimumSize(new java.awt.Dimension(70, 25));
        txtSexo.setPreferredSize(new java.awt.Dimension(70, 25));
        jPanel49.add(txtSexo);

        txtFecha.setEditable(false);
        txtFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFecha.setMaximumSize(new java.awt.Dimension(90, 25));
        txtFecha.setMinimumSize(new java.awt.Dimension(90, 25));
        txtFecha.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel49.add(txtFecha);

        txtPeso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPeso.setMaximumSize(new java.awt.Dimension(65, 25));
        txtPeso.setMinimumSize(new java.awt.Dimension(65, 25));
        txtPeso.setPreferredSize(new java.awt.Dimension(65, 25));
        txtPeso.addKeyListener(control);
        jPanel49.add(txtPeso);

        txtTalla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTalla.setMaximumSize(new java.awt.Dimension(65, 25));
        txtTalla.setMinimumSize(new java.awt.Dimension(65, 25));
        txtTalla.setPreferredSize(new java.awt.Dimension(65, 25));
        txtTalla.addKeyListener(control);
        jPanel49.add(txtTalla);

        txtPesoTalla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPesoTalla.setMaximumSize(new java.awt.Dimension(65, 25));
        txtPesoTalla.setMinimumSize(new java.awt.Dimension(65, 25));
        txtPesoTalla.setPreferredSize(new java.awt.Dimension(65, 25));
        txtPesoTalla.addKeyListener(control);
        jPanel49.add(txtPesoTalla);

        cBoxSevenN.setToolTipText("Sistema de Vigilancia Nutricional");
        jPanel49.add(cBoxSevenN);

        jPanel41.add(jPanel49, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("      REGISTAR DATOS     ", new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Eccd.png")), jPanel1); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 222, 235));

        jPanel6.setBackground(new java.awt.Color(204, 222, 235));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Eccd", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel19.setText("Introducir Número de Caso:");

        txtNumeroCasoBusqueda.setActionCommand("buscarE");
        txtNumeroCasoBusqueda.addActionListener(control);
        txtNumeroCasoBusqueda.addKeyListener(control);

        btnBuscarModificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Buscar.png"))); // NOI18N
        btnBuscarModificacion.setText("Buscar");
        btnBuscarModificacion.setActionCommand("buscarE");
        btnBuscarModificacion.addActionListener(control);

        dateFechaRegistroEdicion.setMaximumSize(new java.awt.Dimension(190, 20));
        dateFechaRegistroEdicion.setMinimumSize(new java.awt.Dimension(190, 20));
        dateFechaRegistroEdicion.setPreferredSize(new java.awt.Dimension(190, 20));

        jLabel20.setText("Gestion :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroCasoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateFechaRegistroEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarModificacion)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(txtNumeroCasoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20))
                    .addComponent(btnBuscarModificacion)
                    .addComponent(dateFechaRegistroEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel22.setBackground(new java.awt.Color(204, 222, 235));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jPanel23.setBackground(new java.awt.Color(255, 243, 189));
        jPanel23.setMaximumSize(new java.awt.Dimension(645, 85));
        jPanel23.setLayout(new java.awt.BorderLayout());

        jPanel24.setBackground(new java.awt.Color(255, 243, 189));
        jPanel24.setMaximumSize(new java.awt.Dimension(625, 60));
        jPanel24.setMinimumSize(new java.awt.Dimension(625, 60));
        jPanel24.setPreferredSize(new java.awt.Dimension(625, 60));
        jPanel24.setLayout(new javax.swing.BoxLayout(jPanel24, javax.swing.BoxLayout.LINE_AXIS));

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Nº CASO");
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel28.setMaximumSize(new java.awt.Dimension(65, 60));
        jLabel28.setMinimumSize(new java.awt.Dimension(65, 60));
        jLabel28.setPreferredSize(new java.awt.Dimension(65, 60));
        jPanel24.add(jLabel28);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("NOMBRE");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel29.setMaximumSize(new java.awt.Dimension(140, 60));
        jLabel29.setMinimumSize(new java.awt.Dimension(140, 60));
        jLabel29.setPreferredSize(new java.awt.Dimension(140, 60));
        jPanel24.add(jLabel29);

        jPanel25.setBackground(new java.awt.Color(255, 243, 189));
        jPanel25.setMaximumSize(new java.awt.Dimension(70, 60));
        jPanel25.setLayout(new java.awt.BorderLayout());

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("SEXO");
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel30.setMaximumSize(new java.awt.Dimension(70, 30));
        jLabel30.setMinimumSize(new java.awt.Dimension(70, 30));
        jLabel30.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel25.add(jLabel30, java.awt.BorderLayout.PAGE_START);

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("F/M");
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel31.setMaximumSize(new java.awt.Dimension(70, 30));
        jLabel31.setMinimumSize(new java.awt.Dimension(70, 30));
        jLabel31.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel25.add(jLabel31, java.awt.BorderLayout.CENTER);

        jPanel24.add(jPanel25);

        jPanel26.setBackground(new java.awt.Color(255, 243, 189));
        jPanel26.setMaximumSize(new java.awt.Dimension(90, 60));
        jPanel26.setLayout(new java.awt.BorderLayout());

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("NCTO.");
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel32.setMaximumSize(new java.awt.Dimension(90, 30));
        jLabel32.setMinimumSize(new java.awt.Dimension(90, 30));
        jLabel32.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel26.add(jLabel32, java.awt.BorderLayout.CENTER);

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("FECHA");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel33.setMaximumSize(new java.awt.Dimension(90, 30));
        jLabel33.setMinimumSize(new java.awt.Dimension(90, 30));
        jLabel33.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel26.add(jLabel33, java.awt.BorderLayout.PAGE_START);

        jPanel24.add(jPanel26);

        jPanel27.setBackground(new java.awt.Color(255, 243, 189));
        jPanel27.setMaximumSize(new java.awt.Dimension(65, 60));
        jPanel27.setLayout(new java.awt.BorderLayout());

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Kgrs.");
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel34.setMaximumSize(new java.awt.Dimension(65, 30));
        jLabel34.setMinimumSize(new java.awt.Dimension(65, 30));
        jLabel34.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel27.add(jLabel34, java.awt.BorderLayout.CENTER);

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("PESO");
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel35.setMaximumSize(new java.awt.Dimension(65, 30));
        jLabel35.setMinimumSize(new java.awt.Dimension(65, 30));
        jLabel35.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel27.add(jLabel35, java.awt.BorderLayout.PAGE_START);

        jPanel24.add(jPanel27);

        jPanel28.setBackground(new java.awt.Color(255, 243, 189));
        jPanel28.setMaximumSize(new java.awt.Dimension(65, 60));
        jPanel28.setLayout(new java.awt.BorderLayout());

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Cms.");
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel36.setMaximumSize(new java.awt.Dimension(65, 30));
        jLabel36.setMinimumSize(new java.awt.Dimension(65, 30));
        jLabel36.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel28.add(jLabel36, java.awt.BorderLayout.CENTER);

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("TALLA");
        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel37.setMaximumSize(new java.awt.Dimension(65, 30));
        jLabel37.setMinimumSize(new java.awt.Dimension(65, 30));
        jLabel37.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel28.add(jLabel37, java.awt.BorderLayout.PAGE_START);

        jPanel24.add(jPanel28);

        jPanel29.setBackground(new java.awt.Color(255, 243, 189));
        jPanel29.setMaximumSize(new java.awt.Dimension(65, 60));
        jPanel29.setLayout(new java.awt.BorderLayout());

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("TALLA");
        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel38.setMaximumSize(new java.awt.Dimension(65, 30));
        jLabel38.setMinimumSize(new java.awt.Dimension(65, 30));
        jLabel38.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel29.add(jLabel38, java.awt.BorderLayout.CENTER);

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("PESO/");
        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel39.setMaximumSize(new java.awt.Dimension(65, 30));
        jLabel39.setMinimumSize(new java.awt.Dimension(65, 30));
        jLabel39.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel29.add(jLabel39, java.awt.BorderLayout.PAGE_START);

        jPanel24.add(jPanel29);

        jPanel30.setBackground(new java.awt.Color(255, 243, 189));
        jPanel30.setMaximumSize(new java.awt.Dimension(65, 60));
        jPanel30.setLayout(new java.awt.BorderLayout());

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("(SVEN)");
        jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel40.setMaximumSize(new java.awt.Dimension(65, 30));
        jLabel40.setMinimumSize(new java.awt.Dimension(65, 30));
        jLabel40.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel30.add(jLabel40, java.awt.BorderLayout.CENTER);

        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("EST.NUT.");
        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel41.setMaximumSize(new java.awt.Dimension(65, 30));
        jLabel41.setMinimumSize(new java.awt.Dimension(65, 30));
        jLabel41.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel30.add(jLabel41, java.awt.BorderLayout.PAGE_START);

        jPanel24.add(jPanel30);

        jPanel23.add(jPanel24, java.awt.BorderLayout.CENTER);

        jPanel31.setMaximumSize(new java.awt.Dimension(625, 25));
        jPanel31.setMinimumSize(new java.awt.Dimension(625, 25));
        jPanel31.setPreferredSize(new java.awt.Dimension(625, 25));
        jPanel31.setLayout(new javax.swing.BoxLayout(jPanel31, javax.swing.BoxLayout.LINE_AXIS));

        txtNroCasoE.setEditable(false);
        txtNroCasoE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNroCasoE.setMaximumSize(new java.awt.Dimension(65, 25));
        txtNroCasoE.setMinimumSize(new java.awt.Dimension(65, 25));
        txtNroCasoE.setPreferredSize(new java.awt.Dimension(65, 25));
        jPanel31.add(txtNroCasoE);

        txtNombreE.setEditable(false);
        txtNombreE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombreE.setMaximumSize(new java.awt.Dimension(140, 25));
        txtNombreE.setMinimumSize(new java.awt.Dimension(140, 25));
        txtNombreE.setPreferredSize(new java.awt.Dimension(140, 25));
        jPanel31.add(txtNombreE);

        txtSexoE.setEditable(false);
        txtSexoE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSexoE.setMaximumSize(new java.awt.Dimension(70, 25));
        txtSexoE.setMinimumSize(new java.awt.Dimension(70, 25));
        txtSexoE.setPreferredSize(new java.awt.Dimension(70, 25));
        jPanel31.add(txtSexoE);

        txtFechaE.setEditable(false);
        txtFechaE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFechaE.setMaximumSize(new java.awt.Dimension(90, 25));
        txtFechaE.setMinimumSize(new java.awt.Dimension(90, 25));
        txtFechaE.setPreferredSize(new java.awt.Dimension(90, 25));
        jPanel31.add(txtFechaE);

        txtPesoE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPesoE.setMaximumSize(new java.awt.Dimension(65, 25));
        txtPesoE.setMinimumSize(new java.awt.Dimension(65, 25));
        txtPesoE.setPreferredSize(new java.awt.Dimension(65, 25));
        txtPesoE.addKeyListener(control);
        jPanel31.add(txtPesoE);

        txtTallaE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTallaE.setMaximumSize(new java.awt.Dimension(65, 25));
        txtTallaE.setMinimumSize(new java.awt.Dimension(65, 25));
        txtTallaE.setPreferredSize(new java.awt.Dimension(65, 25));
        txtTallaE.addKeyListener(control);
        jPanel31.add(txtTallaE);

        txtPesoTallaE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPesoTallaE.setMaximumSize(new java.awt.Dimension(65, 25));
        txtPesoTallaE.setMinimumSize(new java.awt.Dimension(65, 25));
        txtPesoTallaE.setPreferredSize(new java.awt.Dimension(65, 25));
        txtPesoTallaE.addKeyListener(control);
        jPanel31.add(txtPesoTallaE);

        cBoxSevenE.setToolTipText("Sistema de Vigilancia Nutricional");
        jPanel31.add(cBoxSevenE);

        jPanel23.add(jPanel31, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel39.setBackground(new java.awt.Color(255, 243, 189));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Modificar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setActionCommand("modificar");
        btnModificar.addActionListener(control);

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnModificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnModificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jPanel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        jTabbedPane1.addTab("     MODIFICAR DATOS     ", new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Eccd.png")), jPanel2); // NOI18N

        jPanel3.setBackground(new java.awt.Color(204, 222, 235));

        jPanel7.setBackground(new java.awt.Color(204, 222, 235));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Eccd", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel21.setText("Introducir Número de Caso:");

        txtNumeroCasoEliminacion.setActionCommand("buscarX");
        txtNumeroCasoEliminacion.addActionListener(control);
        txtNumeroCasoEliminacion.addKeyListener(control);

        btnBuscarEliminacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Buscar.png"))); // NOI18N
        btnBuscarEliminacion.setText("Buscar");
        btnBuscarEliminacion.setActionCommand("buscarX");
        btnBuscarEliminacion.addActionListener(control);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroCasoEliminacion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnBuscarEliminacion)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtNumeroCasoEliminacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEliminacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel85.setBackground(new java.awt.Color(204, 222, 235));
        jPanel85.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccionar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTableEliminar1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3"
            }
        ));
        jScrollPane7.setViewportView(jTableEliminar1);

        javax.swing.GroupLayout jPanel85Layout = new javax.swing.GroupLayout(jPanel85);
        jPanel85.setLayout(jPanel85Layout);
        jPanel85Layout.setHorizontalGroup(
            jPanel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel85Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel85Layout.setVerticalGroup(
            jPanel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel85Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel38.setBackground(new java.awt.Color(255, 243, 189));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setActionCommand("eliminar");
        btnEliminar.addActionListener(control);

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(282, 282, 282))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel85, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel85, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("     ELIMINAR DATOS     ", new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Eccd.png")), jPanel3); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, 0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel22, 0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiEccd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEliminacion;
    private javax.swing.JButton btnBuscarModificacion;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox cBoxSevenE;
    private javax.swing.JComboBox cBoxSevenN;
    private com.toedter.calendar.JDateChooser dateFechaRegistroEdicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel85;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableEliminar1;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFechaE;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreE;
    private javax.swing.JTextField txtNroCaso;
    private javax.swing.JTextField txtNroCasoE;
    private javax.swing.JTextField txtNumeroCasoBusqueda;
    private javax.swing.JTextField txtNumeroCasoEliminacion;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPesoE;
    private javax.swing.JTextField txtPesoTalla;
    private javax.swing.JTextField txtPesoTallaE;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtSexoE;
    private javax.swing.JTextField txtTalla;
    private javax.swing.JTextField txtTallaE;
    // End of variables declaration//GEN-END:variables
    public CGuiEccd control;

    public JButton getBtnBuscarEliminacion() {
        return btnBuscarEliminacion;
    }

    public JButton getBtnBuscarModificacion() {
        return btnBuscarModificacion;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JButton getBtnModificar() {
        return btnModificar;
    }

    public JButton getBtnNuevo() {
        return btnNuevo;
    }

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public JTextField getTxtFecha() {
        return txtFecha;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

   
    public JTextField getTxtNroCaso() {
        return txtNroCaso;
    }

    public JTextField getTxtNumeroCasoBusqueda() {
        return txtNumeroCasoBusqueda;
    }

    public JTextField getTxtNumeroCasoEliminacion() {
        return txtNumeroCasoEliminacion;
    }

    public JTextField getTxtPeso() {
        return txtPeso;
    }

    public JTextField getTxtPesoTalla() {
        return txtPesoTalla;
    }

    public JTextField getTxtSexo() {
        return txtSexo;
    }


    public JTextField getTxtTalla() {
        return txtTalla;
    }

    public JTextField getTxtFechaE() {
        return txtFechaE;
    }

    public JTextField getTxtNombreE() {
        return txtNombreE;
   }

    public JTextField getTxtNroCasoE() {
        return txtNroCasoE;
    }

     public JTextField getTxtPesoE() {
        return txtPesoE;
    }

    public JTextField getTxtPesoTallaE() {
        return txtPesoTallaE;
    }

    public JTextField getTxtSexoE() {
        return txtSexoE;
    }


    public JTextField getTxtTallaE() {
        return txtTallaE;
    }

    public JTable getjTableEliminar1() {
        return jTableEliminar1;
    }

    public JDateChooser getDateFechaRegistroEdicion() {
        return dateFechaRegistroEdicion;
    }

    public JComboBox getcBoxSevenE() {
        return cBoxSevenE;
    }

    public JComboBox getcBoxSevenN() {
        return cBoxSevenN;
    }

    
}
