/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GuiTarjetaBuscador.java
 *
 * Created on 23-feb-2011, 23:27:01
 */

package view;

import bo.usfx.nuevoAmanecer.controller.CGuiTarjetaBuscador;
import com.toedter.calendar.JDateChooser;
import java.awt.Cursor;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;


public class GuiTarjetaBuscador extends javax.swing.JDialog {

    /** Creates new form GuiTarjetaBuscador */
    public GuiTarjetaBuscador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        control = new CGuiTarjetaBuscador(this);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOpcionesBusqueda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTextoBusqueda = new javax.swing.JTextField();
        dateFechaBusqueda = new com.toedter.calendar.JDateChooser();
        btnBuscar = new javax.swing.JButton();
        pnlBotones = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTarjetas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 111));

        pnlOpcionesBusqueda.setBackground(new java.awt.Color(204, 222, 235));
        pnlOpcionesBusqueda.setPreferredSize(new java.awt.Dimension(463, 40));
        pnlOpcionesBusqueda.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jLabel1.setText("Introduzca el Texto de Busqueda :");
        pnlOpcionesBusqueda.add(jLabel1);

        txtTextoBusqueda.setToolTipText("Introduzca el Texto de Busqueda que desea que sea de filtro para encontrar la familia");
        txtTextoBusqueda.setPreferredSize(new java.awt.Dimension(250, 20));
        txtTextoBusqueda.setActionCommand("buscar");
        txtTextoBusqueda.addActionListener(control);
        //txtTextoBusqueda.addKeyListener(control);
        pnlOpcionesBusqueda.add(txtTextoBusqueda);
        pnlOpcionesBusqueda.add(dateFechaBusqueda);

        btnBuscar.setText("Buscar");
        btnBuscar.setActionCommand("buscar");
        btnBuscar.setMnemonic('B');
        btnBuscar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(control);
        pnlOpcionesBusqueda.add(btnBuscar);

        getContentPane().add(pnlOpcionesBusqueda, java.awt.BorderLayout.PAGE_START);

        pnlBotones.setBackground(new java.awt.Color(255, 243, 189));
        pnlBotones.setPreferredSize(new java.awt.Dimension(400, 35));
        pnlBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnAceptar.setText("Aceptar");
        btnAceptar.setActionCommand("aceptar");
        btnAceptar.setMnemonic('A');
        btnAceptar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnAceptar.addActionListener(control);
        pnlBotones.add(btnAceptar);

        btnCancelar.setText("Cancelar");
        btnCancelar.setActionCommand("cancelar");
        btnCancelar.setMnemonic('C');
        btnCancelar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(control);
        pnlBotones.add(btnCancelar);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        pnlCentral.setPreferredSize(new java.awt.Dimension(561, 300));
        pnlCentral.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(204, 222, 235));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patrocinadores Encontrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 9))); // NOI18N

        jTableTarjetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableTarjetas);

        pnlCentral.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GuiTarjetaBuscador dialog = new GuiTarjetaBuscador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private com.toedter.calendar.JDateChooser dateFechaBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTarjetas;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlOpcionesBusqueda;
    private javax.swing.JTextField txtTextoBusqueda;
    // End of variables declaration//GEN-END:variables
    public CGuiTarjetaBuscador control;

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JTable getjTableTarjetas() {
        return jTableTarjetas;
    }

    public JTextField getTxtTextoBusqueda() {
        return txtTextoBusqueda;
    }

    public JDateChooser getDateFechaBusqueda() {
        return dateFechaBusqueda;
    }

    

}
