/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GuiUsuarios.java
 *
 * Created on 16-ene-2011, 0:51:46
 */

package view;

import bo.usfx.nuevoAmanecer.controller.CGuiUsuarios;
import java.awt.Cursor;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;


public class GuiUsuarios extends javax.swing.JFrame {

    /** Creates new form GuiUsuarios */
    public GuiUsuarios() {
        control = new CGuiUsuarios(this);
        initComponents();
        this.setPreferredSize(new Dimension(350,120));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneUsuarios = new javax.swing.JTabbedPane();
        pnlDatosCampos = new javax.swing.JPanel();
        pnlCentral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFechaRegistro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombreCuenta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        cBoxEstadoActual = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cboxTipoUsuario = new javax.swing.JComboBox();
        pnlBotones = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        pnlNavegacion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        pnlPatronBusqueda = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtTextoBusqueda = new javax.swing.JTextField();
        btnBuscarNavegacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de Usuarios");
        setMinimumSize(new java.awt.Dimension(350, 118));

        pnlDatosCampos.setLayout(new java.awt.BorderLayout());

        pnlCentral.setBackground(new java.awt.Color(204, 222, 235));
        pnlCentral.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        pnlCentral.setMinimumSize(new java.awt.Dimension(350, 57));

        jLabel1.setText("Codigo de usuario:");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlCentral.add(jLabel1);

        txtCodigoUsuario.setEditable(false);
        txtCodigoUsuario.setPreferredSize(new java.awt.Dimension(160, 20));
        pnlCentral.add(txtCodigoUsuario);

        jLabel2.setText("Fecha Registro:");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlCentral.add(jLabel2);

        txtFechaRegistro.setEditable(false);
        txtFechaRegistro.setPreferredSize(new java.awt.Dimension(160, 20));
        pnlCentral.add(txtFechaRegistro);

        jLabel3.setText("Nombres:");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlCentral.add(jLabel3);

        txtNombres.setPreferredSize(new java.awt.Dimension(160, 20));
        txtNombres.addKeyListener(control);
        pnlCentral.add(txtNombres);

        jLabel4.setText("Apellidos:");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlCentral.add(jLabel4);

        txtApellidos.setPreferredSize(new java.awt.Dimension(160, 20));
        txtApellidos.addKeyListener(control);
        pnlCentral.add(txtApellidos);

        jLabel5.setText("Nombre Cuenta:");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlCentral.add(jLabel5);

        txtNombreCuenta.setPreferredSize(new java.awt.Dimension(160, 20));
        pnlCentral.add(txtNombreCuenta);

        jLabel6.setText("Contraseña:");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlCentral.add(jLabel6);

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setPreferredSize(new java.awt.Dimension(160, 20));
        pnlCentral.add(jPasswordField1);

        jLabel7.setText("Estado Actual:");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlCentral.add(jLabel7);

        cBoxEstadoActual.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIGENTE", "DE BAJA", "SUSPENDIDO"}));
        cBoxEstadoActual.setPreferredSize(new java.awt.Dimension(160, 20));
        pnlCentral.add(cBoxEstadoActual);

        jLabel9.setText("Dirección:");
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlCentral.add(jLabel9);

        txtDireccion.setPreferredSize(new java.awt.Dimension(160, 20));
        pnlCentral.add(txtDireccion);

        jLabel10.setText("Telefono:");
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 14));
        pnlCentral.add(jLabel10);

        txtTelefono.setPreferredSize(new java.awt.Dimension(160, 20));
        pnlCentral.add(txtTelefono);

        jLabel11.setText("Tipo responsabilidad");
        pnlCentral.add(jLabel11);

        cboxTipoUsuario.setPreferredSize(new java.awt.Dimension(160, 20));
        pnlCentral.add(cboxTipoUsuario);

        pnlDatosCampos.add(pnlCentral, java.awt.BorderLayout.CENTER);

        pnlBotones.setBackground(new java.awt.Color(255, 243, 189));
        pnlBotones.setMinimumSize(new java.awt.Dimension(350, 33));
        pnlBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setActionCommand("nuevo");
        btnNuevo.addActionListener(control);
        btnNuevo.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnNuevo.setToolTipText("Nuevo Usuario");
        pnlBotones.add(btnNuevo);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Modificar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setActionCommand("modificar");
        btnModificar.addActionListener(control);
        btnModificar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnModificar.setToolTipText("Modificar datos del Usuario");
        pnlBotones.add(btnModificar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Eliminar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setActionCommand("cancelar");
        btnCancelar.addActionListener(control);
        btnCancelar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCancelar.setToolTipText("Cancelar Operación actual");
        pnlBotones.add(btnCancelar);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setActionCommand("guardar");
        btnGuardar.addActionListener(control);
        btnGuardar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnGuardar.setToolTipText("Guardar cambios realizados");
        pnlBotones.add(btnGuardar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Dar de Baja.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setActionCommand("eliminar");
        btnEliminar.addActionListener(control);
        btnEliminar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnEliminar.setToolTipText("Eliminar Usuario Actual");
        pnlBotones.add(btnEliminar);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setActionCommand("buscar");
        btnBuscar.addActionListener(control);
        btnBuscar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnBuscar.setToolTipText("buscar usuarios");
        pnlBotones.add(btnBuscar);

        pnlDatosCampos.add(pnlBotones, java.awt.BorderLayout.SOUTH);

        jTabbedPaneUsuarios.addTab("Registro de Usuarios", pnlDatosCampos);

        pnlNavegacion.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(204, 222, 235));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableUsuarios);

        pnlNavegacion.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlPatronBusqueda.setBackground(new java.awt.Color(204, 222, 235));
        pnlPatronBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese los dato de busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        pnlPatronBusqueda.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jLabel8.setText("Texto de Busqueda :");
        pnlPatronBusqueda.add(jLabel8);

        txtTextoBusqueda.setPreferredSize(new java.awt.Dimension(300, 20));
        txtTextoBusqueda.setActionCommand("buscarN");
        txtTextoBusqueda.addActionListener(control);
        pnlPatronBusqueda.add(txtTextoBusqueda);

        btnBuscarNavegacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Buscar.png"))); // NOI18N
        btnBuscarNavegacion.setText("Buscar");
        btnBuscarNavegacion.setActionCommand("buscarN");
        btnBuscarNavegacion.addActionListener(control);
        btnBuscarNavegacion.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnBuscarNavegacion.setToolTipText("buscar usuarios");
        pnlPatronBusqueda.add(btnBuscarNavegacion);

        pnlNavegacion.add(pnlPatronBusqueda, java.awt.BorderLayout.NORTH);

        jTabbedPaneUsuarios.addTab("Busqueda y Navegación", pnlNavegacion);

        getContentPane().add(jTabbedPaneUsuarios, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarNavegacion;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cBoxEstadoActual;
    private javax.swing.JComboBox cboxTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneUsuarios;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlDatosCampos;
    private javax.swing.JPanel pnlNavegacion;
    private javax.swing.JPanel pnlPatronBusqueda;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCodigoUsuario;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaRegistro;
    private javax.swing.JTextField txtNombreCuenta;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTextoBusqueda;
    // End of variables declaration//GEN-END:variables
    public CGuiUsuarios control;
    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public JButton getBtnBuscarNavegacion() {
        return btnBuscarNavegacion;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public JButton getBtnModificar() {
        return btnModificar;
    }

    public JButton getBtnNuevo() {
        return btnNuevo;
    }


    public JComboBox getcBoxEstadoActual() {
        return cBoxEstadoActual;
    }

    public JPasswordField getjPasswordField1() {
        return jPasswordField1;
    }

    public JTextField getTxtApellidos() {
        return txtApellidos;
    }

    public JTextField getTxtCodigoUsuario() {
        return txtCodigoUsuario;
    }

    public JTextField getTxtFechaRegistro() {
        return txtFechaRegistro;
    }

    public JTextField getTxtNombreCuenta() {
        return txtNombreCuenta;
    }

    public JTextField getTxtNombres() {
        return txtNombres;
    }

    public JTable getjTableUsuarios() {
        return jTableUsuarios;
    }

    public JTextField getTxtTextoBusqueda() {
        return txtTextoBusqueda;
    }

    public JPanel getPnlCentral() {
        return pnlCentral;
    }

    public JTextField getTxtDireccion() {
        return txtDireccion;
    }

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPaneUsuarios;
    }

    public JComboBox getCboxTipoUsuario() {
        return cboxTipoUsuario;
    }

    public JTabbedPane getjTabbedPaneUsuarios() {
        return jTabbedPaneUsuarios;
    }

    public JPanel getPnlDatosCampos() {
        return pnlDatosCampos;
    }

    public JPanel getPnlNavegacion() {
        return pnlNavegacion;
    }
    
    
}
