/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GuiVerTarjetaFamiliar.java
 *
 * Created on 21-feb-2011, 10:33:12
 */

package view;

import bo.usfx.nuevoAmanecer.controller.CGuiVerTarjetaFamiliar;
import java.awt.Cursor;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Silvana
 */
public class GuiVerTarjetaFamiliar extends javax.swing.JFrame {

    /** Creates new form GuiVerTarjetaFamiliar */
    public GuiVerTarjetaFamiliar() {
        control = new CGuiVerTarjetaFamiliar(this);
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlDatosTarjeta = new javax.swing.JPanel();
        pnlCentral = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTableTarjeta = new javax.swing.JTable();
        pnlObservaciones = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        pnlListadoMiembros = new javax.swing.JPanel();
        pnlListadoCentral = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableListadoMiembrosTarjeta = new javax.swing.JTable();
        pnlInferior = new javax.swing.JPanel();
        pnlECCD = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableECCD = new javax.swing.JTable();
        pnlVacunas = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableVacunas = new javax.swing.JTable();
        pnlSuperiorBusqueda = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroTarjetaBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblNroTarjeta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tarjeta Familiar");

        jTabbedPane1.setBackground(new java.awt.Color(204, 222, 235));

        pnlDatosTarjeta.setLayout(new java.awt.BorderLayout());

        pnlCentral.setBackground(new java.awt.Color(204, 222, 235));
        pnlCentral.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Tarjeta Familiar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        pnlCentral.setLayout(new java.awt.BorderLayout());

        jTableTarjeta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4", "Título 5", "Título 6", "Título 7"
            }
        ));
        jScrollPane9.setViewportView(jTableTarjeta);

        pnlCentral.add(jScrollPane9, java.awt.BorderLayout.CENTER);

        pnlDatosTarjeta.add(pnlCentral, java.awt.BorderLayout.CENTER);

        pnlObservaciones.setBackground(new java.awt.Color(204, 222, 235));
        pnlObservaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Observaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        pnlObservaciones.setPreferredSize(new java.awt.Dimension(991, 150));
        pnlObservaciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jLabel2.setText("Observaciones Generales");
        pnlObservaciones.add(jLabel2);

        txtObservaciones.setEditable(false);
        txtObservaciones.setRows(2);
        txtObservaciones.setMaximumSize(new java.awt.Dimension(500, 30));
        txtObservaciones.setPreferredSize(new java.awt.Dimension(750, 58));
        jScrollPane1.setViewportView(txtObservaciones);

        pnlObservaciones.add(jScrollPane1);

        jLabel3.setText("Descripción de Domicilio");
        jLabel3.setPreferredSize(new java.awt.Dimension(122, 14));
        pnlObservaciones.add(jLabel3);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtDireccion.setEditable(false);
        txtDireccion.setRows(2);
        txtDireccion.setMaximumSize(new java.awt.Dimension(500, 30));
        txtDireccion.setPreferredSize(new java.awt.Dimension(750, 58));
        jScrollPane2.setViewportView(txtDireccion);

        pnlObservaciones.add(jScrollPane2);

        pnlDatosTarjeta.add(pnlObservaciones, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("Datos de la Tarjeta", pnlDatosTarjeta);

        pnlListadoMiembros.setLayout(new java.awt.BorderLayout());

        pnlListadoCentral.setBackground(new java.awt.Color(204, 222, 235));
        pnlListadoCentral.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Miembros correspondientes a la Tarjeta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        pnlListadoCentral.setLayout(new java.awt.BorderLayout());

        jTableListadoMiembrosTarjeta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4", "Título 5", "Título 6", "Título 7"
            }
        ));
        jScrollPane6.setViewportView(jTableListadoMiembrosTarjeta);

        pnlListadoCentral.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        pnlListadoMiembros.add(pnlListadoCentral, java.awt.BorderLayout.CENTER);

        pnlInferior.setPreferredSize(new java.awt.Dimension(991, 200));
        pnlInferior.setLayout(new java.awt.GridLayout(1, 2));

        pnlECCD.setBackground(new java.awt.Color(204, 222, 235));
        pnlECCD.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "ECCD Afiliado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        pnlECCD.setLayout(new java.awt.BorderLayout());

        jTableECCD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4", "Título 5", "Título 6", "Título 7"
            }
        ));
        jScrollPane7.setViewportView(jTableECCD);

        pnlECCD.add(jScrollPane7, java.awt.BorderLayout.CENTER);

        pnlInferior.add(pnlECCD);

        pnlVacunas.setBackground(new java.awt.Color(204, 222, 235));
        pnlVacunas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "VACUNAS Afiliado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        pnlVacunas.setLayout(new java.awt.BorderLayout());

        jTableVacunas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4", "Título 5", "Título 6", "Título 7"
            }
        ));
        jScrollPane8.setViewportView(jTableVacunas);

        pnlVacunas.add(jScrollPane8, java.awt.BorderLayout.CENTER);

        pnlInferior.add(pnlVacunas);

        pnlListadoMiembros.add(pnlInferior, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("Listado de Miembros", pnlListadoMiembros);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pnlSuperiorBusqueda.setBackground(new java.awt.Color(204, 222, 235));
        pnlSuperiorBusqueda.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText("Numero de Tarjeta:");
        pnlSuperiorBusqueda.add(jLabel4);

        txtNumeroTarjetaBusqueda.setPreferredSize(new java.awt.Dimension(250, 20));
        txtNumeroTarjetaBusqueda.setActionCommand("buscar");
        txtNumeroTarjetaBusqueda.addActionListener(control);
        txtNumeroTarjetaBusqueda.addKeyListener(control);
        pnlSuperiorBusqueda.add(txtNumeroTarjetaBusqueda);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagenes/Buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setActionCommand("buscar");
        btnBuscar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnBuscar.setToolTipText("Buscar por el Número de Tarjeta");
        btnBuscar.setMnemonic('B');
        btnBuscar.addActionListener(control);
        pnlSuperiorBusqueda.add(btnBuscar);

        lblNroTarjeta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNroTarjeta.setForeground(new java.awt.Color(63, 120, 204));
        lblNroTarjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNroTarjeta.setText("TARJETA FAMILIA");
        pnlSuperiorBusqueda.add(lblNroTarjeta);
        lblNroTarjeta.getAccessibleContext().setAccessibleName("TARJETA FAMILIA NRO");

        getContentPane().add(pnlSuperiorBusqueda, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiVerTarjetaFamiliar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableECCD;
    private javax.swing.JTable jTableListadoMiembrosTarjeta;
    private javax.swing.JTable jTableTarjeta;
    private javax.swing.JTable jTableVacunas;
    private javax.swing.JLabel lblNroTarjeta;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlDatosTarjeta;
    private javax.swing.JPanel pnlECCD;
    private javax.swing.JPanel pnlInferior;
    private javax.swing.JPanel pnlListadoCentral;
    private javax.swing.JPanel pnlListadoMiembros;
    private javax.swing.JPanel pnlObservaciones;
    private javax.swing.JPanel pnlSuperiorBusqueda;
    private javax.swing.JPanel pnlVacunas;
    private javax.swing.JTextArea txtDireccion;
    private javax.swing.JTextField txtNumeroTarjetaBusqueda;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public JTable getjTableECCD() {
        return jTableECCD;
    }

    public JTable getjTableListadoMiembrosTarjeta() {
        return jTableListadoMiembrosTarjeta;
    }

    public JTable getjTableTarjeta() {
        return jTableTarjeta;
    }

    public JTable getjTableVacunas() {
        return jTableVacunas;
    }

    public JLabel getLblNroTarjeta() {
        return lblNroTarjeta;
    }

    public JPanel getPnlCentral() {
        return pnlCentral;
    }

    public JPanel getPnlDatosTarjeta() {
        return pnlDatosTarjeta;
    }

    public JPanel getPnlECCD() {
        return pnlECCD;
    }

    public JPanel getPnlInferior() {
        return pnlInferior;
    }

    public JPanel getPnlListadoCentral() {
        return pnlListadoCentral;
    }

    public JTextArea getTxtDireccion() {
        return txtDireccion;
    }

    public JTextField getTxtNumeroTarjetaBusqueda() {
        return txtNumeroTarjetaBusqueda;
    }

    public JTextArea getTxtObservaciones() {
        return txtObservaciones;
    }

    public CGuiVerTarjetaFamiliar control;
    
}
